git:
  depth: 10
sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - '14'

env:
  - JOB=test

script:
  - 'if [ "$JOB" = "test" ]; then npm test; fi'
  - 'if [ "$JOB" = "lint" ]; then npm run lint; fi'

matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: JOB=lint

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      # Generate with
      #     travis encrypt "babeljs:<token>#activity" --add notifications.slack.rooms
      # where <token> is from the Slack integration settings.
      secure: SrwPKRe2AiNAKRo/+2yW/x4zxbWf2FBXuBuuPkdTJVTpWe++Jin1lXYJWTKP1a1i/IbmhffBO9YZcUFbeuXJpRM083vO8VYpyuBMQRqWD+Z3o+ttPlHGOJgnj0nkIcGRk6k7PpyHNnIkixfEJDvbbg9lN1Jswb3xkL8iYIHpuFE=
